image: docker
services:
  - docker:dind
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/study-nuxt .
    - docker run -d -p 80:80 --rm --name studyNuxtApp app/study-nuxt
